### ISSUE TITLE
Hmm

### ISSUE THREAD

**Issue by alluding** [sammorozov/go_basics_study#1]
No clue if you meant double pointer as in a pointer (`x`) that is pointing to an `int`, and then dereferencing `x` to double its value, storing the result back into `x` to return the doubled value, but this is a single pointer. A double pointer would be like `pp`, which is a pointer to a pointer to an `int` (i.e., `**int`). `*pp` dereferences `pp` to get the pointer to an `int`, and `*(*pp)` dereferences this pointer to get the `int` value, which can then be manipulated. This is a real double pointer.

**Comment by sammorozov** [comment]
I agree, it's an unfortunate name for a function and I perfectly understand what a real double pointer is. The author of the course on the platform chose an unfortunate name for a function that was supposed to pass tests under this name.
